### ISSUE TITLE
still more columns to show kada?

### ISSUE THREAD

**Issue by nknnkumar** [keshavsoft/LaundryMan#18]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/115708070/196391126-86b7035f-8b16-4784-b8b5-87ea5a63e652.png">

**Comment by Tulasi1920** [comment]
Sir same order Lona sir

**Comment by Tulasi1920** [comment]
done sir Check PR

**Comment by nknnkumar** [comment]
make the order column as button
and try to write click event for that buttons
to navigate to another screen like
last booking got it?

**Comment by Tulasi1920** [comment]
ok sir

**Comment by Tulasi1920** [comment]
just now tested sir good working sir

**Comment by Tulasi1920** [comment]
like visually like marking on screenshot

**Comment by Tulasi1920** [comment]
sir reply?
