### ISSUE TITLE
masters:customers click check header colour

### ISSUE THREAD

**Issue by nknnkumar** [keshavsoft/LaundryMan#33]
![image](https://user-images.githubusercontent.com/115708070/196890058-853ba335-3df7-40bb-ab48-ae9dc7870c1e.png)

![image](https://user-images.githubusercontent.com/115708070/196890183-6ddc6643-00cc-4892-875e-645349fdcd69.png)

see above
i am in insert but show is colour

**Comment by Tulasi1920** [comment]
sir but it working for me
